/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_Red.h"
#include "Pin_Red_aliases.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "LED2.h"
#include "LED2_aliases.h"
#include "LED3.h"
#include "LED3_aliases.h"
#include "MOSFET1.h"
#include "MOSFET1_aliases.h"
#include "LED4.h"
#include "LED4_aliases.h"
#include "LED5.h"
#include "LED5_aliases.h"
#include "LED6.h"
#include "LED6_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

